repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.6.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==19.10b0]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
          - id: trailing-whitespace
            #- id: check-added-large-files
            #args:
            #    - --maxkb=128
          - id: check-ast
          - id: check-builtin-literals
          - id: check-byte-order-marker
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
          - id: check-xml
          - id: check-yaml
          - id: debug-statements
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: name-tests-test
            args:
                - --django
            exclude: ^tests/testapp|^tests/management/|^tests/collisions/|^tests/pythonrc.py
            #    - repo: https://github.com/miki725/importanize
            #      rev: "0.7"
            #      hooks:
            #          - id: importanize
            #            language_version: python3
            #    - repo: https://github.com/PyCQA/pydocstyle
            #      rev: 6de6d938377e2db3bfe6f706fa2e3b90c412db76
            #      hooks:
            #          - id: pydocstyle
    # - repo: https://github.com/PyCQA/bandit
    #   rev: "1.6.0"
    #   hooks:
    #       - id: bandit
    #    - repo: https://github.com/prettier/prettier
    #      rev: "1.18.2"
    #      hooks:
    #          - id: prettier
    #            args: ["--print-width 120"]
    # additional_dependencies: ['prettier@1.1.0']
    # - repo: https://github.com/adrienverge/yamllint
    #   rev: "v1.16.0"
    #   hooks:
    #       - id: yamllint
  - repo: git://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.1.7
    hooks:
      - id: forbid-crlf
  - repo: git://github.com/trbs/pre-commit-hooks-trbs.git
    rev: e233916fb2b4b9019b4a3cc0497994c7926fe36b
    hooks:
      - id: forbid-executables
        exclude: manage.py|setup.py|docker-entrypoint.sh|mariadb-backup.sh|email2nip.py
