---
version: "3.5"

networks:
    geoda2_net:
        ipam:
            driver: default
            config:
                - subnet: 172.101.0.0/24

services:
    db:
        command: |
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_unicode_ci
            --sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,ANSI_QUOTES,NO_AUTO_CREATE_USER
            --transaction-isolation=READ-COMMITTED
        env_file: ./env/common.env
        image: mariadb:10.5
        networks:
            geoda2_net:
                ipv4_address: 172.101.0.2
        ports:
            - '3307:3306'
        restart: always
        volumes:
            - ./data:/var/lib/mysql

    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: uwsgi
        env_file:
            - ./env/common.env
            - ./env/geoda2.env
        depends_on:
            - db
        networks:
            geoda2_net:
                ipv4_address: 172.101.0.3
        ports:
            - protocol: tcp
              published: 8001
              target: 8001
        restart: on-failure
