# Generated by Django 2.2.2 on 2019-06-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("geo", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="curso",
            options={
                "permissions": [
                    ("cursos_pendientes", "Puede ver el listado de cursos por aprobar.")
                ]
            },
        )
    ]
