# Generated by Django 2.1 on 2019-01-11 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignaturaSigma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id_nk', models.IntegerField(blank=True, null=True, verbose_name='Cód. plan')),
                ('nombre_estudio', models.CharField(blank=True, max_length=254, null=True, verbose_name='Estudio')),
                ('centro_id', models.IntegerField(blank=True, null=True, verbose_name='Cód. centro')),
                ('nombre_centro', models.CharField(blank=True, max_length=150, null=True, verbose_name='Centro')),
                ('tipo_estudio_id', models.IntegerField(blank=True, null=True, verbose_name='Cód. tipo estudio')),
                ('nombre_tipo_estudio', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de estudio')),
                ('asignatura_id', models.IntegerField(blank=True, null=True, verbose_name='Cód. asignatura')),
                ('nombre_asignatura', models.CharField(blank=True, max_length=120, null=True, verbose_name='Asignatura')),
                ('prela_cu', models.CharField(blank=True, max_length=5, null=True)),
                ('tipo_periodo', models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo de periodo')),
                ('valor_periodo', models.CharField(blank=True, max_length=2, null=True, verbose_name='Periodo')),
                ('cod_grupo_asignatura', models.IntegerField(blank=True, null=True, verbose_name='Grupo')),
                ('turno', models.CharField(blank=True, max_length=1, null=True)),
                ('tipo_docencia', models.IntegerField(blank=True, null=True, verbose_name='Tipo de docencia')),
                ('anyo_academico', models.IntegerField(blank=True, null=True, verbose_name='Año académico')),
                ('edicion', models.IntegerField(blank=True, null=True, verbose_name='Edición')),
            ],
            options={
                'db_table': 'asignatura_sigma',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma_id', models.IntegerField(blank=True, null=True, verbose_name='Cód. plataforma')),
                ('id_nk', models.CharField(blank=True, max_length=45, null=True, verbose_name='Cód. en plataforma')),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('centro_id', models.IntegerField(blank=True, null=True, verbose_name='Cód. centro')),
                ('plan_id_nk', models.IntegerField(blank=True, null=True, verbose_name='Cód. plan')),
                ('anyo_academico', models.IntegerField(blank=True, null=True, verbose_name='Año académico')),
                ('supercategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geo.Categoria', verbose_name='Categoría padre')),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de solicitud')),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de autorización')),
                ('plataforma_id', models.IntegerField(blank=True, null=True, verbose_name='Cód. plataforma')),
                ('id_nk', models.CharField(blank=True, max_length=45, null=True, verbose_name='Código en plataforma')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creación')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL')),
                ('anyo_academico', models.IntegerField(blank=True, null=True, verbose_name='Año académico')),
                ('motivo_solicitud', models.TextField(blank=True, null=True, verbose_name='Motivo de la solicitud')),
                ('motivo_denegacion', models.TextField(blank=True, null=True, verbose_name='Motivo de la denegación')),
                ('asignatura_sigma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geo.AsignaturaSigma', unique=True, verbose_name='Asignatura Sigma')),
                ('autorizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geo.Categoria', verbose_name='Categoría')),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=127, null=True)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.AlterField(
            model_name='pod',
            name='nip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='NIP'),
        ),
        migrations.AlterIndexTogether(
            name='pod',
            index_together={('nip', 'anyo_academico')},
        ),
        migrations.AddField(
            model_name='curso',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geo.Estado'),
        ),
        migrations.AlterUniqueTogether(
            name='asignaturasigma',
            unique_together={('plan_id_nk', 'asignatura_id', 'cod_grupo_asignatura', 'centro_id', 'anyo_academico')},
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('anyo_academico', 'centro_id', 'plan_id_nk')},
        ),
    ]
