# Generated by Django 2.2.2 on 2019-06-28 10:20
# https://docs.djangoproject.com/en/2.2/howto/writing-migrations/

from django.db import migrations


def add_managers_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    group, created = Group.objects.get_or_create(name='Gestores')
    if created:
        print('Creado el grupo «Gestores».')
        cursos_pendientes = Permission.objects.get(codename='cursos_pendientes')
        group.permissions.add(cursos_pendientes)


class Migration(migrations.Migration):

    dependencies = [('geo', '0002_auto_20190628_1214')]

    operations = [migrations.RunPython(add_managers_group)]
