# Generated by Django 2.2 on 2019-06-19 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geo", "0002_auto_20190111_2337"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calendario",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="Año académico"
                    ),
                )
            ],
            options={"db_table": "calendario"},
        ),
        migrations.AlterModelOptions(
            name="asignaturasigma",
            options={
                "verbose_name": "asignatura SIGM@",
                "verbose_name_plural": "asignaturas SIGM@",
            },
        ),
        migrations.AlterModelOptions(
            name="categoria", options={"verbose_name": "categoría"}
        ),
        migrations.AlterField(
            model_name="categoria",
            name="anyo_academico",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="Año académico"
            ),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="centro_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="Cód. centro"
            ),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="supercategoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.Categoria",
                verbose_name="Categoría padre",
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="asignatura_sigma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.AsignaturaSigma",
                unique=True,
                verbose_name="Asignatura Sigma",
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="autorizador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.Categoria",
                verbose_name="Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="estado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.Estado",
            ),
        ),
        migrations.AlterField(
            model_name="curso", name="nombre", field=models.CharField(max_length=200)
        ),
        migrations.CreateModel(
            name="ProfesorCurso",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fecha_alta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de alta"
                    ),
                ),
                (
                    "fecha_baja",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de baja"
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="geo.Curso"
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "profesor_curso"},
        ),
        migrations.AddField(
            model_name="curso",
            name="profesores",
            field=models.ManyToManyField(
                related_name="profesores",
                through="geo.ProfesorCurso",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
