# Generated by Django 2.2.3 on 2019-07-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('geo', '0003_auto_20190628_1220')]

    sql = """CREATE VIEW "MoodleProfesores" AS
    SELECT
        "pc"."curso_id" AS "cursoId",
        "u"."username" AS "username",
        IF (("c"."anyo_academico" < 2015), 'noenrolingteacher', 'editingteacher')
            AS "Rol",
        "u"."email" AS "email"
    FROM
        "profesor_curso" "pc"
        JOIN "curso" "c" ON "pc"."curso_id" = "c"."id"
        JOIN "accounts_customuser" "u" ON "pc"."profesor_id" = "u"."id"
    WHERE
        "u"."is_active" = 1
        AND "c"."estado" = 3
        AND "c"."anyo_academico" > 2011
        AND (ISNULL("pc"."fecha_baja") OR ("pc"."fecha_baja" = ''))
        AND "c"."id_nk" IS NOT NULL
        AND "c"."plataforma_id" = 1
        AND "u"."email" IS NOT NULL
    ;
    """

    reverse_sql = 'DROP VIEW MoodleProfesores;'

    operations = [migrations.RunSQL(sql, reverse_sql)]
