# Generated by Django 2.2.3 on 2019-08-21 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('geo', '0004_auto_20190718_1203')]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='asignatura',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='geo.Asignatura',
                verbose_name='Asignatura',
            ),
        ),
        migrations.AlterField(
            model_name='curso',
            name='comentarios',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
    ]
