# Generated by Django 2.2.3 on 2019-08-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("geo", "0005_auto_20190821_0955")]

    operations = [
        migrations.AlterModelOptions(
            name="calendario",
            options={
                "permissions": [
                    ("calendario", "Puede modificar el año académico actual.")
                ]
            },
        ),
        migrations.AddField(
            model_name="calendario",
            name="anyo",
            field=models.PositiveSmallIntegerField(
                default=2019, verbose_name="Año académico"
            ),
        ),
        migrations.AddField(
            model_name="calendario",
            name="slug",
            field=models.SlugField(default="actual", unique=True),
        ),
        migrations.AlterField(
            model_name="calendario",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
