# Generated by Django 2.2.8 on 2019-12-12 09:00

from django.db import migrations


def crear_estados_predefinidos(apps, schema_editor):
    valores = (
        (1, "Solicitado"),
        (2, "Autorizado"),
        (3, "Creado"),
        (4, "Suspendido"),
        (5, "Borrado"),
        (6, "Denegado"),
    )
    Estado = apps.get_model("geo", "Estado")
    for numero, nombre in valores:
        Estado.objects.get_or_create(id=numero, nombre=nombre)


class Migration(migrations.Migration):

    dependencies = [("geo", "0007_auto_20190909_0835")]

    operations = [migrations.RunPython(crear_estados_predefinidos)]
