# Generated by Django 3.0.4 on 2020-03-10 11:21

from django.apps import apps as django_apps
from django.contrib.auth.management import create_permissions
from django.db import migrations, models


def migrate_permissions(apps, schema_editor):
    """Create the pending permissions.

    Permissions are not actually created during or after an individual migration,
    but are triggered by a post-migrate signal which is sent after the
    `python manage.py migrate` command completes successfully.

    This is necessary so that we can add the permission to a group in this migration.
    """
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=2)
        app_config.models_module = None


def add_permission_to_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    gestores = Group.objects.get(name='Gestores')

    cursos_creados = Permission.objects.get(codename='cursos_creados')
    gestores.permissions.add(cursos_creados)


class Migration(migrations.Migration):

    dependencies = [('geo', '0007_auto_20190909_0835')]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={
                'ordering': ('anyo_academico', 'nombre'),
                'permissions': [
                    ('cursos_creados', 'Puede ver el listado de cursos creados.'),
                    ('cursos_pendientes', 'Puede ver el listado de cursos por aprobar.'),
                ],
            },
        ),
        migrations.RunPython(migrate_permissions),
        migrations.RunPython(add_permission_to_group),
    ]
