# Generated by Django 3.0.4 on 2020-03-12 12:54

from django.contrib.auth.management import create_permissions
from django.db import migrations, models


def migrate_permissions(apps, schema_editor):
    """Create the pending permissions.

    Permissions are not actually created during or after an individual migration,
    but are triggered by a post-migrate signal which is sent after the
    `python manage.py migrate` command completes successfully.

    This is necessary so that we can add the permission to a group in this migration.
    """
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=2)
        app_config.models_module = None


def add_permission_to_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    gestores = Group.objects.get(name='Gestores')

    matricular_plan = Permission.objects.get(codename='matricular_plan')
    gestores.permissions.add(matricular_plan)


class Migration(migrations.Migration):
    dependencies = [('geo', '0009_auto_20200310_1221')]

    operations = [
        migrations.CreateModel(
            name='RightsSupport',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                )
            ],
            options={
                'permissions': (
                    (
                        'matricular_plan',
                        'Puede matricular en un curso a todos los alumnos de un plan',
                    ),
                ),
                'managed': False,
            },
        ),
        migrations.RunPython(migrate_permissions),
        migrations.RunPython(add_permission_to_group),
    ]
