# Generated by Django 3.0.7 on 2020-09-18 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0017_auto_20200904_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forano',
            name='nip',
            field=models.PositiveIntegerField(
                help_text='Número de Identificación Personal del usuario a vincular.',
                validators=[
                    django.core.validators.MinValueValidator(100001),
                    django.core.validators.MaxValueValidator(999999),
                ],
                verbose_name='NIP a vincular',
            ),
        ),
    ]
