# Generated by Django 3.2.8 on 2021-10-18 08:56

from django.apps import apps as django_apps
from django.contrib.auth.management import create_permissions
from django.db import migrations, models


def migrate_permissions(apps, schema_editor):
    """Create the pending permissions.

    Permissions are not actually created during or after an individual migration,
    but are triggered by a post-migrate signal which is sent after the
    `python manage.py migrate` command completes successfully.

    This is necessary so that we can add the permission to a group in this migration.
    """
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=2)
        app_config.models_module = None


def add_permission_to_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    gestores = Group.objects.get(name='Gestores')

    anyadir_alumnos = Permission.objects.get(codename='anyadir_alumnos')
    gestores.permissions.add(anyadir_alumnos)


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0020_auto_20210105_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightssupport',
            options={
                'managed': False,
                'permissions': (
                    (
                        'matricular_plan',
                        'Puede matricular en un curso a todos los alumnos de un plan',
                    ),
                    ('anyadir_alumnos', 'Puede matricular alumnos en un curso'),
                ),
            },
        ),
        migrations.RunPython(migrate_permissions),
        migrations.RunPython(add_permission_to_group),
    ]
