# Generated by Django 4.1.6 on 2023-02-07 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0023_centro_estudio_alter_asignatura_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='cod_grupo_asignatura',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='Cód. grupo de la asignatura'
            ),
        ),
        migrations.AlterField(
            model_name='forano',
            name='nip',
            field=models.PositiveIntegerField(
                help_text='Número de Identificación Personal del usuario a vincular.',
                validators=[
                    django.core.validators.MinValueValidator(100001),
                    django.core.validators.MaxValueValidator(9999999),
                ],
                verbose_name='NIP a vincular',
            ),
        ),
        migrations.AlterField(
            model_name='matriculaautomatica',
            name='active',
            field=models.BooleanField(default=False, verbose_name='¿Activo?'),
        ),
        migrations.AlterField(
            model_name='matriculaautomatica',
            name='asignatura_id',
            field=models.IntegerField(
                blank=True,
                help_text='Puede consultar el código de una asignatura'
                ' en la <a href="https://estudios.unizar.es">web de estudios</a>.',
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10001),
                    django.core.validators.MaxValueValidator(999999),
                ],
                verbose_name='Cód. asignatura',
            ),
        ),
        migrations.AlterField(
            model_name='matriculaautomatica',
            name='cod_grupo_asignatura',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='Cód. grupo de la asignatura'
            ),
        ),
        migrations.AlterField(
            model_name='matriculaautomatica',
            name='fijo',
            field=models.BooleanField(default=False, verbose_name='¿Registro predefinido?'),
        ),
        migrations.AlterField(
            model_name='matriculacion',
            name='cod_grupo_asignatura',
            field=models.IntegerField(verbose_name='Cód. grupo de la asignatura'),
        ),
        migrations.AlterField(
            model_name='pod',
            name='cod_grupo_asignatura',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='Cód. grupo de la asignatura'
            ),
        ),
    ]
