# Generated by Django 4.2 on 2023-05-05 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0025_alter_matriculaautomatica_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='cod_ep',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Cód. estudio propio'),
        ),
        migrations.AddField(
            model_name='plan',
            name='cod_ep',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Cód. estudio propio'),
        ),
        migrations.AlterField(
            model_name='matriculaautomatica',
            name='asignatura_id',
            field=models.IntegerField(
                blank=True,
                help_text='Puede consultar el código de una asignatura en la <a href="https://estudios.unizar.es">web de estudios</a> <span class="fas fa-link"></span>.',
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10001),
                    django.core.validators.MaxValueValidator(999999),
                ],
                verbose_name='Cód. asignatura',
            ),
        ),
    ]
