# Generated by Django 4.2 on 2023-05-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0026_estudio_cod_ep_plan_cod_ep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='id',
            field=models.PositiveIntegerField(
                primary_key=True, serialize=False, verbose_name='Cód. estudio'
            ),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.PositiveIntegerField(
                primary_key=True, serialize=False, verbose_name='Cód. plan'
            ),
        ),
    ]
