# Generated by Django 4.2.1 on 2023-06-28 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0027_alter_estudio_id_alter_plan_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matriculaautomatica',
            unique_together={
                ('asignatura_id', 'cod_grupo_asignatura', 'plan', 'courseid', 'centro')
            },
        ),
        migrations.AlterField(
            model_name='matriculaautomatica',
            name='asignatura_id',
            field=models.IntegerField(
                blank=True,
                help_text='Puede consultar el código de una asignatura en la <a href="https://estudios.unizar.es" target="_blank">web de estudios</a> <span class="fas fa-link"></span>.',
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10001),
                    django.core.validators.MaxValueValidator(999999),
                ],
                verbose_name='Cód. asignatura',
            ),
        ),
    ]
