# Generated by Django 4.2.4 on 2023-09-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0028_alter_matriculaautomatica_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaautomatica',
            name='cod_grupo_asignatura',
            field=models.IntegerField(
                blank=True,
                help_text='Déjelo en blanco para seleccionar <strong>todos</strong> los grupos.',
                null=True,
                verbose_name='Cód. grupo de la asignatura',
            ),
        ),
    ]
