# Generated by Django 4.2.4 on 2023-09-18 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0030_alter_asignatura_asignatura_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaautomatica',
            name='centro',
            field=models.ForeignKey(
                blank=True,
                help_text='Tenga en cuenta que un mismo código de asignatura se puede impartir en varios centros.',
                limit_choices_to={'esta_activo': True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='geo.centro',
            ),
        ),
        migrations.AlterField(
            model_name='matriculaautomatica',
            name='plan',
            field=models.ForeignKey(
                blank=True,
                help_text='Tenga en cuenta que un mismo código de asignatura se puede impartir en varios planes.',
                limit_choices_to={'esta_activo': True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='geo.plan',
            ),
        ),
    ]
