# Generated by Django 4.2.6 on 2023-10-10 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0031_alter_matriculaautomatica_centro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculaautomatica',
            name='sigmacentro',
        ),
        migrations.RemoveField(
            model_name='matriculaautomatica',
            name='sigmacourseid',
        ),
        migrations.RemoveField(
            model_name='matriculaautomatica',
            name='sigmagroupid',
        ),
        migrations.RemoveField(
            model_name='matriculaautomatica',
            name='sigmatitu',
        ),
    ]
