# Generated by Django 5.0.7 on 2024-07-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0033_alter_forano_options_alter_forano_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matriculaautomatica',
            old_name='asignatura_id',
            new_name='asignatura_nk',
        ),
        migrations.AlterUniqueTogether(
            name='matriculaautomatica',
            unique_together={
                ('asignatura_nk', 'cod_grupo_asignatura', 'plan', 'courseid', 'centro')
            },
        ),
    ]
