# Generated by Django 5.0.7 on 2024-07-17 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0034_rename_asignatura_id_matriculaautomatica_asignatura_nk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculaautomatica',
            name='curso',
            field=models.ForeignKey(
                default=42, on_delete=django.db.models.deletion.PROTECT, to='geo.curso'
            ),
            preserve_default=False,
        ),
    ]
