# Generated by Django 5.1.1 on 2024-09-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0035_matriculaautomatica_curso'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pod',
            new_name='pod_nip_anyo_academico_idx',
            old_fields=('nip', 'anyo_academico'),
        ),
    ]
